name: ci

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:

env:
  GO111MODULE: on

jobs:
  golangci:
    name: lint
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v7
      - name: Set up stable Go version
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Get dependencies
        run: go mod tidy
      - name: Lint code with golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2
          only-new-issues: true
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.25.x', 'stable']
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v7
      - name: Get dependencies
        run: go mod tidy
      - name: Tests
        run: |
          go install gotest.tools/gotestsum@latest
          gotestsum --format testdox ./... -v -cpu 2 -timeout 30s -race -cover -coverprofile=coverage.out -covermode=atomic
      - name: Coverage
        uses: codecov/codecov-action@v3
